// AUTOGENERATED by scripts/export_types.py — do not edit by hand.
// Source: app/api/schemas/*.py (Pydantic v2 models)
export interface AlertOut {
  id: number;
  kind: string;
  severity: string;
  status: string;
  score_v2?: number | string | null;
  official_id?: string | null;
  ticker_id?: string | null;
  related_transaction_id?: number | null;
  payload: Record<string, unknown>;
  created_at: string;
  acknowledged_at?: string | null;
  resolved_at?: string | null;
  expiry_at?: string | null;
  dismissed_at?: string | null;
}

export interface AcknowledgeAlertResponse {
  id: number;
  status: string;
  acknowledged_at?: string | null;
  resolved_at?: string | null;
  expiry_at?: string | null;
}

export interface NewsEventOut {
  /** Surrogate row id (BIGSERIAL). */
  id: number;
  event_id: string;
  event_date: string;
  source_url?: string | null;
  actor1_name?: string | null;
  actor2_name?: string | null;
  event_code?: string | null;
  tone?: number | string | null;
  article_count?: number | null;
  headline?: string | null;
  domain?: string | null;
  mentioned_companies: Record<string, unknown>[];
  mentioned_officials: Record<string, unknown>[];
  ingested_at: string;
}

export interface BacktestRunRequest {
  /** Reference strategy name. One of: 'q1_vote_trade_inconsistency', 'beyer_sector', 'cluster_fire', 'null_baseline'. */
  strategy: string;
  /** Backtest start (inclusive). Defaults to 24 months before end_date. */
  start_date?: string | null;
  /** Backtest end (inclusive). Defaults to today. */
  end_date?: string | null;
  /** Override the strategy's default hold period in days. */
  hold_days?: number | null;
}

export interface BacktestRunSummary {
  run_id: string;
  strategy_name: string;
  status: string;
  start_date: string;
  end_date: string;
  /** Decimal-string of the initial capital used for the run. */
  initial_capital: string;
  universe_filter: Record<string, unknown>;
  entry_signal: Record<string, unknown>;
  exit_rule: Record<string, unknown>;
  error_message?: string | null;
  created_at: string;
  completed_at?: string | null;
}

export interface BacktestMetricsOut {
  /** Portfolio total return as a decimal. */
  total_return: number;
  /** Calendar-time-annualized portfolio return as a decimal. */
  annualized_return: number;
  /** Annualized Sharpe ratio assuming 0 risk-free rate. NULL when return variance is zero (e.g. zero trades). */
  sharpe?: number | null;
  /** Annualized Sortino ratio. NULL when no negative-return trades exist. */
  sortino?: number | null;
  /** Maximum peak-to-trough equity-curve drawdown as a decimal. */
  max_drawdown: number;
  /** Fraction of trades with positive P&L. */
  win_rate: number;
  /** Mean position holding period in days. */
  avg_holding_days: number;
  n_trades: number;
  n_winners: number;
  n_losers: number;
  /** Decimal-string of ending equity. */
  final_equity: string;
}

export interface BacktestRunResponse {
  run_id: string;
  strategy_name: string;
  status: string;
  start_date: string;
  end_date: string;
  /** Decimal-string of the initial capital used for the run. */
  initial_capital: string;
  universe_filter: Record<string, unknown>;
  entry_signal: Record<string, unknown>;
  exit_rule: Record<string, unknown>;
  error_message?: string | null;
  created_at: string;
  completed_at?: string | null;
  /** Computed metrics; NULL until the run is COMPLETED. */
  metrics?: BacktestMetricsOut | null;
}

export interface BacktestTradeOut {
  id: number;
  run_id: string;
  entry_date: string;
  exit_date: string;
  ticker_id: string;
  position_size: string;
  entry_price: string;
  exit_price: string;
  pnl: string;
  return_pct: number;
  source_alert_id?: number | null;
  source_transaction_id?: number | null;
  official_id?: string | null;
  exit_reason: string;
  notes?: Record<string, unknown> | null;
}

export interface OfficialSummary {
  id: string;
  bioguide_id?: string | null;
  full_name: string;
  party?: string | null;
  chamber?: string | null;
}

export interface TickerSummary {
  id: string;
  symbol: string;
  exchange?: string | null;
  instrument_type: string;
}

export interface ClusterMemberOut {
  official: OfficialSummary;
  /** BIGINT id of the member's earliest transaction inside the cluster window. NULL when the underlying transaction has been deleted. */
  first_transaction_id?: number | null;
}

export interface ClusterOut {
  id: string;
  committee_id: string;
  committee_name: string;
  ticker: TickerSummary;
  direction: string;
  window_start: string;
  window_end: string;
  /** Distinct committee members trading the ticker in the same direction within the 14d window. CHECK enforces >= 3 at the DB layer. */
  member_count: number;
  members?: ClusterMemberOut[];
  created_at: string;
  updated_at: string;
}

export interface PredictiveFeedItem {
  /** Predictive-signal type. Slice 3: 'cluster' or 'hearing_proximity'. Slice 4 adds 'fomc_blackout'. Slice 5 adds 'contract_proximity' and 'high_value_contract'. Slice 6 adds 'lobbying_overlay'. Slice 8 adds 'vote_trade_inconsistency'. Slice 11 adds 'news_trade_proximity'. Slice 12 adds 'statement_trade_contradiction'. Slice 13 adds 'scotus_congressional_overlap'. */
  kind: string;
  /** Relative ranking score within the feed. Higher = stronger signal. Cluster: member_count. Hearing-proximity: 30 - |proximity_days|. FOMC blackout: 100. Contract proximity: 80 (60 - |proximity_days|, boosted by 50 so the rare contract+trade overlap ranks above the more-common hearing-proximity signal). High-value contract: 120 (above FOMC blackout because committee-jurisdiction + >$100M contract is the strongest predictive signal in the catalog). Lobbying overlay: 60-80 base (plain chamber overlap), 100+ with issue-sector match boost. */
  score: number;
  /** Timestamp the signal effectively occurred — cluster.window_end, hearing.scheduled_at, or the Fed trade's transaction_date — used for feed ordering. */
  occurred_at: string;
  /** Display name of the primary trader on the item — the member / fed-official / justice / staffer / state official whose trade (or trade-adjacent signal) triggered the row. NULL for kind='cluster' (which carries N members via nested ClusterOut.members instead of one). Resolved server-side via a single bulk JOIN against officials so the frontend doesn't N+1 /members/{id}. */
  official_name?: string | null;
  cluster?: ClusterOut | null;
  /** Transaction id for kind='hearing_proximity' items. */
  hearing_proximity_transaction_id?: number | null;
  /** Transaction id for kind='fomc_blackout' items. */
  fomc_blackout_transaction_id?: number | null;
  /** Fed-official id for kind='fomc_blackout' items. */
  fomc_blackout_official_id?: string | null;
  /** FOMC meeting id whose blackout window covers the trade. */
  fomc_blackout_meeting_id?: string | null;
  /** Transaction id for kind='contract_proximity' or 'high_value_contract' items. */
  contract_proximity_transaction_id?: number | null;
  /** Official id for contract-proximity / high-value-contract items. */
  contract_proximity_official_id?: string | null;
  /** Contract id from the USAspending ingest the trade is paired with. */
  contract_proximity_contract_id?: string | null;
  /** Award amount as a Decimal-string for precision. Frontend parses back to number for display. */
  contract_proximity_award_amount?: string | null;
  /** USAspending Award ID (PIID/FAIN) for the contract. */
  contract_proximity_award_id?: string | null;
  /** Signed days from transaction_date to award_date. Negative = trade preceded award (predictive); positive = trade followed award. */
  contract_proximity_proximity_days?: number | null;
  /** Transaction id for kind='lobbying_overlay' items. */
  lobbying_overlay_transaction_id?: number | null;
  /** Official id for kind='lobbying_overlay' items. */
  lobbying_overlay_official_id?: string | null;
  /** LDA filing id (lobbying_filings.id) the trade overlaps. */
  lobbying_overlay_filing_id?: string | null;
  /** Company id resolved as the LDA filing's client. Load-bearing for the Slice-7 (member, company, week) dedup work. */
  lobbying_overlay_client_company_id?: string | null;
  /** LDA client name as reported on the filing. */
  lobbying_overlay_client_name?: string | null;
  /** LDA registrant name (the lobbying firm). */
  lobbying_overlay_registrant_name?: string | null;
  /** Signed days from transaction_date to filing_period_end. Negative = trade preceded the period close; positive = trade followed it. */
  lobbying_overlay_proximity_days?: number | null;
  /** LDA general_issue_code list from the filing's activities. */
  lobbying_overlay_issue_codes?: string[];
  /** True when at least one issue_code maps to the company's GICS sector — the boost that pushes the score above the base band. */
  lobbying_overlay_issue_sector_match?: boolean | null;
  /** ISO-week label, e.g. '2025-W31'. Slice 7 will dedup at (member, company, week) using this key. */
  lobbying_overlay_trade_week_id?: string | null;
  /** Filing amount (income or expenses, whichever the registrant reported) as Decimal-string for precision. After Slice 7 aggregation, this is the *summed* amount across all filings in the (member, company, week) bucket. */
  lobbying_overlay_amount_usd?: string | null;
  /** Number of underlying (transaction, contract) pairs folded into this aggregated alert. Slice 7 dedup at (member, company, week). */
  contract_proximity_aggregated_count?: number | null;
  /** Max award amount across the aggregated contracts (Decimal-string). */
  contract_proximity_aggregated_max_amount?: string | null;
  /** ISO week of the aggregation bucket, e.g. '2024-W29'. */
  contract_proximity_iso_week?: string | null;
  /** z = (aggregated_count - baseline_mean) / baseline_std over the company's trailing 24mo 60-day contract volume. NULL when the company has too few baseline windows to compute std. */
  contract_proximity_relative_volume_z_score?: string | null;
  /** Distinct recipient names from the aggregated contracts. */
  contract_proximity_recipient_names?: string[];
  /** Number of MV rows folded into this aggregated lobbying alert. */
  lobbying_overlay_aggregated_count?: number | null;
  /** Distinct LDA filings contributing to the bucket. */
  lobbying_overlay_distinct_filings?: number | null;
  /** z = (aggregated_count - baseline_mean) / baseline_std over the company's trailing 24mo 90-day lobbying volume. */
  lobbying_overlay_relative_volume_z_score?: string | null;
  /** Transaction id for kind='vote_trade_inconsistency' items. */
  vote_inconsistency_transaction_id?: number | null;
  /** Member who cast the contradictory vote. */
  vote_inconsistency_official_id?: string | null;
  /** Roll-call vote id whose member position contradicts the trade direction. */
  vote_inconsistency_vote_id?: string | null;
  /** Company id of the traded ticker. */
  vote_inconsistency_company_id?: string | null;
  /** Display name of the traded company. */
  vote_inconsistency_company_name?: string | null;
  /** GICS sector of the traded company. */
  vote_inconsistency_company_gics_sector?: string | null;
  /** HOUSE or SENATE; chamber the vote was cast in. */
  vote_inconsistency_chamber?: string | null;
  /** Procedural question text from the roll-call (e.g. 'On Passage'). */
  vote_inconsistency_vote_question?: string | null;
  /** Bill / topic description (e.g. 'American Relief Act, 2025'). */
  vote_inconsistency_vote_description?: string | null;
  /** Legislative number (e.g. 'H R 10545') when the vote is bill-attached. */
  vote_inconsistency_legis_num?: string | null;
  /** The member's recorded position (YEA or NAY for CONTRADICTORY rows). */
  vote_inconsistency_member_position?: string | null;
  /** BUY or SELL — the trade direction whose direction contradicted the vote. */
  vote_inconsistency_trade_direction?: string | null;
  /** Sector of the bill subject (matches the trade's company sector by join). */
  vote_inconsistency_primary_gics_sector?: string | null;
  /** BENEFICIAL / HARMFUL / NEUTRAL — direction of impact a YEA vote has on the sector. */
  vote_inconsistency_sector_impact?: string | null;
  /** Signed days between transaction_date and vote_date. Negative = trade before vote. */
  vote_inconsistency_proximity_days?: number | null;
  /** True when the underlying roll-call had a margin <= 10 (close vote / likely party-line break). Boosts /feed/predictive ranking. */
  vote_inconsistency_key_vote?: boolean | null;
  /** Total YEA tally on the underlying roll-call. */
  vote_inconsistency_yeas?: number | null;
  /** Total NAY tally on the underlying roll-call. */
  vote_inconsistency_nays?: number | null;
  /** ISO week label of the trade ('2025-W31'); reserved for future Slice 11 aggregation compatibility. */
  vote_inconsistency_trade_week_id?: string | null;
  /** related_transaction_id on the underlying NEWS_TRADE_PROXIMITY alert. */
  news_proximity_transaction_id?: number | null;
  /** UUID of the member; mirrors the alert's official_id column. */
  news_proximity_official_id?: string | null;
  /** news_events.id of the linked news event. */
  news_proximity_news_event_db_id?: number | null;
  /** Event date of the linked news article (used for partition lookup). */
  news_proximity_news_event_date?: string | null;
  /** Absolute day delta |transaction_date - event_date| (0..14). */
  news_proximity_proximity_days?: number | null;
  /** GDELT AvgTone of the article; lower (more negative) = stronger signal. */
  news_proximity_tone?: number | null;
  /** Article headline as reported by the GDELT Doc API. */
  news_proximity_headline?: string | null;
  /** URL of the source article. */
  news_proximity_source_url?: string | null;
  /** Alert id for kind='statement_trade_contradiction' items. */
  statement_contradiction_alert_id?: number | null;
  /** Transaction id the alert points at. */
  statement_contradiction_transaction_id?: number | null;
  /** Member who made the statement and the trade. */
  statement_contradiction_official_id?: string | null;
  /** member_statements.id for the contradicting statement. */
  statement_contradiction_statement_db_id?: number | null;
  /** Date the statement was made (≤ transaction_date by 90d). */
  statement_contradiction_statement_date?: string | null;
  /** URL of the statement (bill / press release). */
  statement_contradiction_statement_source_url?: string | null;
  /** One of FLOOR_SPEECH, PRESS_RELEASE, TWITTER, INTERVIEW, OP_ED. */
  statement_contradiction_statement_source_type?: string | null;
  /** GICS sector the contradiction applies to. */
  statement_contradiction_gics_sector?: string | null;
  /** Sector sentiment of the statement, [-1, 1]. Negative = opposes; positive = supports. BUY_AFTER_OPPOSITION fires when score ≤ -0.3; SELL_AFTER_SUPPORT fires when score ≥ +0.3. */
  statement_contradiction_sentiment_score?: number | null;
  /** Trade direction (BUY/SELL). */
  statement_contradiction_trade_direction?: string | null;
  /** Days from statement_date to transaction_date (0..90). */
  statement_contradiction_proximity_days?: number | null;
  /** BUY_AFTER_OPPOSITION or SELL_AFTER_SUPPORT. */
  statement_contradiction_kind?: string | null;
  /** Alert id for kind='scotus_congressional_overlap' items. */
  scotus_overlap_alert_id?: number | null;
  /** UUID of the SCOTUS justice who traded. */
  scotus_overlap_justice_official_id?: string | null;
  /** UUID of the congressional member who traded the same ticker. */
  scotus_overlap_member_official_id?: string | null;
  /** Display name of the congressional member; mirrors scotus_overlap_member_official_id. The justice's name lives in the top-level official_name field (justice is the primary trader). */
  scotus_overlap_member_official_name?: string | null;
  /** judicial_transactions.id for the justice's trade. */
  scotus_overlap_judicial_transaction_id?: number | null;
  /** transactions.id for the congressional trade. */
  scotus_overlap_congressional_transaction_id?: number | null;
  /** Approximate date of the justice's trade. */
  scotus_overlap_justice_trade_date?: string | null;
  /** Date of the congressional trade. */
  scotus_overlap_member_trade_date?: string | null;
  /** BUY/SELL on the justice side. */
  scotus_overlap_justice_trade_direction?: string | null;
  /** BUY/SELL on the congressional side. */
  scotus_overlap_member_trade_direction?: string | null;
  /** |justice_trade_date - member_trade_date|, 0..30. */
  scotus_overlap_proximity_days?: number | null;
  /** True when both trades are the same direction (BUY/BUY or SELL/SELL). */
  scotus_overlap_same_direction?: boolean | null;
  /** Alert id for kind='staffer_trade_proximity' items. */
  staffer_proximity_alert_id?: number | null;
  /** UUID of the senior staffer who traded. */
  staffer_proximity_staffer_official_id?: string | null;
  /** staffer_employments.id giving the inherited jurisdiction. */
  staffer_proximity_employment_id?: number | null;
  /** COMMITTEE_JURISDICTION | MEMBER_CLUSTER. */
  staffer_proximity_overlay_kind?: string | null;
  /** UUID of the staffer's employing committee, when overlay_kind is COMMITTEE_JURISDICTION or the staffer has a committee employment. */
  staffer_proximity_employing_committee_id?: string | null;
  /** UUID of the staffer's employing member, when overlay_kind is MEMBER_CLUSTER or the staffer has a personal-office employment. */
  staffer_proximity_employing_member_id?: string | null;
  /** Display name of the staffer's employing member; mirrors staffer_proximity_employing_member_id. The staffer's own name lives in the top-level official_name field. */
  staffer_proximity_employing_member_name?: string | null;
  /** GICS sector overlap between the traded ticker's company and the employing committee's jurisdiction. Set for COMMITTEE_JURISDICTION. */
  staffer_proximity_matched_sector?: string | null;
  /** transactions.id of the employing member's matched trade (MEMBER_CLUSTER). */
  staffer_proximity_related_member_transaction_id?: number | null;
  /** |staffer_trade_date - member_trade_date|, 0..30 (MEMBER_CLUSTER only). */
  staffer_proximity_proximity_days?: number | null;
  /** Alert id for kind='state_official_trade_proximity' items. */
  state_official_proximity_alert_id?: number | null;
  /** UUID of the state-level official who traded. */
  state_official_proximity_state_official_id?: string | null;
  /** TX | CA | NY | FL — state the official represents. */
  state_official_proximity_state?: string | null;
  /** GOVERNOR | LIEUTENANT_GOVERNOR | STATE_SENATOR | STATE_REP | CABINET | COMMISSIONER | ATTORNEY_GENERAL | TREASURER | SECRETARY_OF_STATE | OTHER. */
  state_official_proximity_office_type?: string | null;
  /** IN_STATE_HQ | CROSS_GOVERNMENT_CLUSTER. */
  state_official_proximity_overlay_kind?: string | null;
  /** Company id of the in-state-HQ company (IN_STATE_HQ overlay). */
  state_official_proximity_company_id?: string | null;
  /** HQ state of the traded company (matches the official's state). */
  state_official_proximity_company_hq_state?: string | null;
  /** UUID of the federal Congress member whose ticker overlap triggered CROSS_GOVERNMENT_CLUSTER. */
  state_official_proximity_related_federal_official_id?: string | null;
  /** Display name of the related federal Congress member; mirrors state_official_proximity_related_federal_official_id. The state official's own name lives in the top-level official_name field. */
  state_official_proximity_related_federal_official_name?: string | null;
  /** transactions.id of the federal member's matched trade. */
  state_official_proximity_related_federal_transaction_id?: number | null;
  /** |state_official_trade_date - federal_trade_date|, 0..30 (CROSS_GOVERNMENT_CLUSTER only). */
  state_official_proximity_proximity_days?: number | null;
}

export interface CommitteeMemberSummary {
  id: string;
  bioguide_id?: string | null;
  full_name: string;
  party?: string | null;
  state?: string | null;
  role: string;
}

export interface HearingSummary {
  id: string;
  scheduled_at: string;
  topic: string;
  status: string;
  location?: string | null;
}

export interface CommitteeDetail {
  id: string;
  chamber: string;
  code: string;
  name: string;
  /** Currently-serving members (memberships with end_date IS NULL) */
  members?: CommitteeMemberSummary[];
  /** Up to the 10 most recent or upcoming hearings, ordered scheduled_at DESC */
  recent_hearings?: HearingSummary[];
}

export interface PageInfo {
  /** Opaque cursor for the next page. NULL on the last page. */
  next_cursor?: string | null;
  /** Whether more pages exist after this one */
  has_more: boolean;
  /** Total count if cheaply computable; NULL for cursor-paginated endpoints */
  total?: number | null;
}

export interface Page {
  items: unknown[];
  page: PageInfo;
}

export interface ErrorEnvelope {
  /** Machine-parseable error code (e.g. 'member_not_found') */
  code: string;
  /** Human-readable error message */
  message: string;
  /** Correlation ID for grepping logs */
  request_id: string;
}

export interface DatedValue {
  /** Calendar date (UTC) */
  d: string;
  /** Count for that day */
  v: number;
}

export interface DashboardSummary {
  /** Count of OPEN alerts */
  active_flagged_count: number;
  /** OPEN alert creation count per day, trailing 14 days inclusive of today */
  active_flagged_series: DatedValue[];
  /** Active cluster count */
  active_clusters_count: number;
}

export interface DistrictMemberSummary {
  official_id: string;
  full_name: string;
  party?: string | null;
  /** HOUSE for districts; SENATE rows have no single member. */
  chamber: string;
  state: string;
  district_num: number | null;
}

export interface DistrictRecentActivity {
  transaction_id?: number | null;
  official_id?: string | null;
  official_name?: string | null;
  ticker?: string | null;
  company_name?: string | null;
  transaction_type?: string | null;
  transaction_date?: string | null;
  amount_max_usd?: string | null;
}

export interface DistrictAlertSummary {
  alert_id: number;
  kind: string;
  severity: string;
  created_at: string;
  official_id: string | null;
  /** Decimal serialized as string; NULL before next recompute pass. */
  score_v2?: string | null;
  related_transaction_id?: number | null;
  headline?: string | null;
}

export interface DistrictOut {
  district_id: string;
  /** HOUSE | SENATE */
  chamber: string;
  state: string;
  /** House district 0-N; NULL for SENATE rows. */
  district_num?: number | null;
  population_2020?: number | null;
  congress_number: number;
  source: string;
  member?: DistrictMemberSummary | null;
  alert_count_90d?: number;
  critical_count_90d?: number;
  recent_activity?: DistrictRecentActivity[];
}

export interface DistrictHeatmapEntry {
  district_id: string;
  state: string;
  district_num: number | null;
  chamber: string;
  alert_count_90d: number;
  critical_count_90d: number;
  alert_count_lifetime: number;
}

export interface DistrictHeatmap {
  items: DistrictHeatmapEntry[];
  generated_at: string;
}

export interface MemberDistrictConcentration {
  official_id: string;
  full_name: string;
  state: string;
  district_num: number | null;
  district_id?: string | null;
  total_trade_count: number;
  in_district_trade_count: number;
  /** Fraction of trades in companies HQ'd in the member's own district; NULL when total_trade_count is 0. */
  district_concentration_ratio?: number | null;
  /** Z-score against the universe baseline of members with ≥5 trades; NULL when baseline stddev is 0 or the member's ratio is NULL. */
  z_score_vs_baseline?: number | null;
  baseline_mean_ratio?: number | null;
  baseline_sd_ratio?: number | null;
}

export interface SourceHealthOut {
  name: string;
  kind: string;
  health_status: string;
  consecutive_failures: number;
  last_run_at?: string | null;
  last_success_at?: string | null;
  last_failure_at?: string | null;
  last_failure_reason?: string | null;
}

export interface IngestionHealthResponse {
  sources: SourceHealthOut[];
}

export interface LeaderboardItem {
  official_id: string;
  full_name: string;
  chamber?: string | null;
  party?: string | null;
  state?: string | null;
  /** Position in the composite-score ranking; NULL when the member has fewer than 10 lifetime trades. */
  rank_overall?: number | null;
  /** 0.4*norm_alpha + 0.3*shrunk_hit_rate + 0.2*filing_quality + 0.1*alert_density. Alpha and hit_rate are Bayesian-shrunk toward their priors (0 and 0.5) with prior_n=20 BUYs to neutralize small-n outliers. ~0-1 with 0.5 = neutral. */
  composite_score?: number | null;
  /** Decimal-string of mean 90-day excess return vs sector ETF. */
  alpha_90d?: string | null;
  /** Decimal-string of % of BUYs with positive 90d excess return. */
  hit_rate_90d?: string | null;
  /** 0-1 (1 = perfect filing quality). See /members/{id}/quality. */
  filing_quality_score?: number | null;
  /** Fraction of disclosed trades filed >45 days after the trade. */
  late_filing_rate?: number | null;
  vagueness_score_avg?: number | null;
  completeness_score?: number | null;
  amendment_rate?: number | null;
  n_trades_lifetime: number;
  n_trades_90d: number;
  alert_count_lifetime: number;
  critical_alert_count_lifetime: number;
  /** True when n_trades_lifetime >= 10. */
  has_sufficient_sample: boolean;
  last_refreshed_at: string;
}

export interface FilingQualityBreakdown {
  official_id: string;
  full_name: string;
  n_transactions: number;
  n_filings: number;
  /** Average days from transaction_date to filed_at. STOCK Act window is 45d. */
  reporting_lag_avg_days?: number | null;
  reporting_lag_p95_days?: number | null;
  /** Fraction filed >45d after the trade. */
  late_filing_rate?: number | null;
  /** Avg vagueness 0-1; 0 = always specific, 1 = always vague. */
  vagueness_score_avg?: number | null;
  /** Fraction of transactions that came in via a later amended filing. */
  amendment_rate?: number | null;
  /** Fraction of transactions with all of (amount_min, amount_max, ticker_id, transaction_date) populated. */
  completeness_score?: number | null;
  /** 0.4*(1-late) + 0.3*(1-vagueness) + 0.2*completeness + 0.1*(1-amendment). 0-1; 1 = perfect. */
  composite_quality_score?: number | null;
  computed_at: string;
}

export interface CommitteeOut {
  id: string;
  name: string;
  chamber: string | null;
  code: string;
}

export interface CommitteeMembershipOut {
  committee: CommitteeOut;
  role: string;
  start_date: string;
  end_date?: string | null;
}

export interface ExternalIdOut {
  system: string;
  external_id: string;
}

export interface StaffWithRecentTrades {
  staffer_id: string;
  staffer_name: string;
  /** e.g. 'Chief of Staff', 'Legislative Director'. */
  office_title?: string | null;
  /** Count of staffer transactions filed in the trailing window (default 90d). */
  recent_trade_count: number;
  /** Most recent transaction_date for this staffer. */
  last_trade_date?: string | null;
}

export interface MemberOut {
  id: string;
  /** The unitedstates/congress-legislators bioguide ID, when applicable */
  bioguide_id?: string | null;
  role_type: string;
  full_name: string;
  party?: string | null;
  chamber?: string | null;
  state?: string | null;
  district?: number | null;
  position_title?: string | null;
  /** Years since first_elected_date, when known */
  tenure_years?: number | null;
  /** Active committee memberships (end_date IS NULL) */
  committees?: CommitteeMembershipOut[];
  external_ids?: ExternalIdOut[];
  /** Staffers employed in this member's office (personal or leadership) who have filed PTRs in the last 90 days. Empty list when no staffers are registered for the office or no recent staff trades exist. */
  staff_with_recent_trades?: StaffWithRecentTrades[];
}

export interface MemberAlphaPoint {
  horizon_days: number;
  /** Disclosed BUYs with both entry + exit closes available */
  n_trades: number;
  /** Decimal-string of mean excess return vs sector ETF (or SPY) over the horizon. Positive = beat the benchmark. NULL when n_trades=0. */
  mean_alpha?: string | null;
  /** Decimal-string of % of trades with positive excess_return at this horizon (0.0-1.0). NULL when n_trades=0. */
  hit_rate?: string | null;
}

export interface MemberAlphaResponse {
  official_id: string;
  full_name: string;
  /** The benchmark methodology used for the alpha calculation */
  benchmark?: string;
  points: MemberAlphaPoint[];
}

export interface DisclosureDecayPoint {
  /** Days after filed_at at which the excess return is measured. 0 = at-disclosure baseline (the trade is now public). */
  horizon_days: number;
  n_trades: number;
  /** Decimal-string of mean excess return vs benchmark. */
  mean_excess_return?: string | null;
}

export interface DisclosureDecayResponse {
  official_id: string;
  full_name: string;
  points: DisclosureDecayPoint[];
}

export interface FedOfficialOut {
  id: string;
  full_name: string;
  /** e.g. 'Chair', 'Vice Chair', 'Member, Federal Reserve Board', 'President, Federal Reserve Bank of <District>'. */
  position_title?: string | null;
  /** Stable slug used as the external_id under system='fed_board_id'. For governors this is the federalreserve.gov bio slug (e.g. 'powell'); for regional presidents it is 'district-<district-slug>' (e.g. 'district-atlanta'). */
  fed_board_id?: string | null;
  /** The Reserve Bank district for regional presidents (e.g. 'new-york', 'san-francisco'). NULL for board governors. */
  district?: string | null;
  /** federalreserve.gov bio or district-index URL. */
  bio_url?: string | null;
  active: boolean;
}

export interface ScotusJusticeOut {
  id: string;
  full_name: string;
  /** e.g. 'Chief Justice', 'Associate Justice'. */
  seat_title?: string | null;
  /** Always 'SCOTUS' for this endpoint. */
  court: string;
  /** Name of the appointing president. */
  appointed_by_president?: string | null;
  /** Year of confirmation to the court. */
  appointed_year?: number | null;
  /** ACTIVE | RETIRED | SENIOR. */
  current_status: string;
  /** The most recent filing_year in `judicial_disclosures` for this justice. NULL if no disclosure has been ingested yet. */
  most_recent_disclosure_year?: number | null;
  /** Total disclosures ingested across all years. */
  disclosure_count?: number;
}

export interface JudicialHoldingOut {
  asset_name: string;
  /** STOCK | BOND | MUTUAL_FUND | REAL_ESTATE | OTHER */
  asset_category: string;
  /** Resolved ticker symbol from the alias table. NULL for mutual funds, real estate, and other non-public-equity assets. */
  ticker?: string | null;
  /** Lower bound of disclosed value range (USD). */
  value_range_low?: number | string | null;
  /** Upper bound of disclosed value range (USD); NULL if unbounded. */
  value_range_high?: number | string | null;
  filing_year: number;
}

export interface JudicialTransactionOut {
  asset_name: string;
  ticker: string | null;
  /** BUY | SELL | EXCHANGE | OTHER */
  transaction_type: string;
  transaction_date_approximate: string | null;
  value_range_low: number | string | null;
  value_range_high: number | string | null;
  filing_year: number;
}

export interface StafferEmploymentOut {
  id: number;
  /** PERSONAL | COMMITTEE | LEADERSHIP */
  employing_office_type: string;
  /** FK to officials. NULL for committee-only employments where the staffer reports directly to a committee chair/ranking member. */
  employing_member_id?: string | null;
  /** Convenience: resolved full_name of the employing member. */
  employing_member_name?: string | null;
  /** FK to committees. NULL for personal-office employments. Both FKs are set when a staffer formally reports to a committee but is assigned to a member's caucus. */
  employing_committee_id?: string | null;
  /** Convenience: resolved name of the employing committee. */
  employing_committee_name?: string | null;
  /** e.g. 'Staff Director', 'Chief of Staff', 'Legislative Director'. */
  office_title?: string | null;
  /** TIER_1 (senior staff cap) | TIER_2 | UNKNOWN. */
  salary_band: string;
  start_date: string;
  end_date: string | null;
  is_current: boolean;
}

export interface StafferOut {
  id: string;
  full_name: string;
  /** HOUSE | SENATE. */
  chamber?: string | null;
  /** Most recent / canonical title (mirrors the office_title of the current employment when one exists). */
  position_title?: string | null;
  /** Total `staffer_employments` rows for this staffer. */
  employment_count?: number;
  /** Best-effort current employment summary. NULL if the staffer has no `is_current=true` employment row. */
  current_employment?: StafferEmploymentOut | null;
}

export interface StaffWithRecentTradesOut {
  staffer_id: string;
  staffer_name: string;
  office_title: string | null;
  /** Count of staffer PTRs filed in the last 90 days. */
  recent_trade_count: number;
  last_trade_date: string | null;
}

export interface StateOfficialOut {
  id: string;
  full_name: string;
  /** TX | CA | NY | FL. */
  state: string;
  /** GOVERNOR | LIEUTENANT_GOVERNOR | STATE_SENATOR | STATE_REP | CABINET | COMMISSIONER | ATTORNEY_GENERAL | TREASURER | SECRETARY_OF_STATE | OTHER. */
  office_type: string;
  /** District number for STATE_SENATOR/STATE_REP; NULL for statewide offices. */
  district?: number | null;
  /** D | R | I | null. */
  party?: string | null;
  /** Current-term start date. */
  term_start?: string | null;
  /** Current-term end date; NULL while serving. */
  term_end?: string | null;
  /** True while term_end is NULL. */
  is_current: boolean;
  /** Free-text role / job title (mirrors office_type for canonical roles). */
  position_title?: string | null;
  /** State-portal canonical id when known. */
  external_id?: string | null;
}

export interface StateOfficialTransactionOut {
  transaction_id: number;
  state_official_id: string;
  state_official_name: string;
  office_type: string;
  state: string;
  ticker: string | null;
  ticker_id: string | null;
  company_name: string | null;
  company_hq_state: string | null;
  transaction_type: string;
  transaction_date: string;
  filed_at: string | null;
  amount_min_usd: string | null;
  amount_max_usd: string | null;
  amount_bucket: string | null;
}

export interface JurisdictionOverlap {
  /** True when ticker's GICS sector matches any of the member's committee sectors */
  flag: boolean;
  /** Names of overlapping committees */
  committees?: string[];
}

export interface HearingProximity {
  hearing_id: string;
  hearing_topic: string;
  hearing_scheduled_at: string;
  committee_id: string;
  committee_name: string;
  /** transaction_date - hearing_date in days. Negative = trade preceded hearing (predictive); positive = trade followed hearing (reactive). */
  proximity_days: number;
}

export interface TransactionOut {
  id: number;
  official: OfficialSummary;
  /** NULL when normalization queued the row for manual review */
  ticker?: TickerSummary | null;
  asset_description: string;
  owner_type: string;
  transaction_type: string;
  transaction_date: string;
  filed_at?: string | null;
  amount_min_usd?: number | string | null;
  amount_max_usd?: number | string | null;
  amount_bucket: string;
  source: string;
  jurisdiction_overlap?: JurisdictionOverlap | null;
  /** Nearest hearing of any committee the member sits on, within ±30d. NULL when no such hearing exists in the window. */
  hearing_proximity?: HearingProximity | null;
  ticker_resolution_confidence?: number | null;
}
