// AUTOGENERATED by scripts/export_types.py — do not edit by hand.
// Source: app/api/schemas/*.py (Pydantic v2 models)

export interface PageInfo {
  /** Opaque cursor for the next page. NULL on the last page. */
  next_cursor?: string | null;
  /** Whether more pages exist after this one */
  has_more: boolean;
  /** Total count if cheaply computable; NULL for cursor-paginated endpoints */
  total?: number | null;
}

export interface Page {
  items: unknown[];
  page: PageInfo;
}

export interface ErrorEnvelope {
  /** Machine-parseable error code (e.g. 'member_not_found') */
  code: string;
  /** Human-readable error message */
  message: string;
  /** Correlation ID for grepping logs */
  request_id: string;
}

export interface SourceHealthOut {
  name: string;
  kind: string;
  health_status: string;
  consecutive_failures: number;
  last_run_at?: string | null;
  last_success_at?: string | null;
  last_failure_at?: string | null;
  last_failure_reason?: string | null;
}

export interface IngestionHealthResponse {
  sources: SourceHealthOut[];
}

export interface CommitteeOut {
  id: string;
  name: string;
  chamber: string | null;
  code: string;
}

export interface CommitteeMembershipOut {
  committee: CommitteeOut;
  role: string;
  start_date: string;
  end_date?: string | null;
}

export interface ExternalIdOut {
  system: string;
  external_id: string;
}

export interface MemberOut {
  id: string;
  /** The unitedstates/congress-legislators bioguide ID, when applicable */
  bioguide_id?: string | null;
  role_type: string;
  full_name: string;
  party?: string | null;
  chamber?: string | null;
  state?: string | null;
  district?: number | null;
  position_title?: string | null;
  /** Years since first_elected_date, when known */
  tenure_years?: number | null;
  /** Active committee memberships (end_date IS NULL) */
  committees?: CommitteeMembershipOut[];
  external_ids?: ExternalIdOut[];
}

export interface TickerSummary {
  id: string;
  symbol: string;
  exchange?: string | null;
  instrument_type: string;
}

export interface OfficialSummary {
  id: string;
  bioguide_id?: string | null;
  full_name: string;
  party?: string | null;
  chamber?: string | null;
}

export interface JurisdictionOverlap {
  /** True when ticker's GICS sector matches any of the member's committee sectors */
  flag: boolean;
  /** Names of overlapping committees */
  committees?: string[];
}

export interface TransactionOut {
  id: number;
  official: OfficialSummary;
  /** NULL when normalization queued the row for manual review */
  ticker?: TickerSummary | null;
  asset_description: string;
  owner_type: string;
  transaction_type: string;
  transaction_date: string;
  filed_at?: string | null;
  amount_min_usd?: number | string | null;
  amount_max_usd?: number | string | null;
  amount_bucket: string;
  source: string;
  jurisdiction_overlap?: JurisdictionOverlap | null;
  ticker_resolution_confidence?: number | null;
}
