/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClustersRouteImport } from './routes/clusters'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MembersIndexRouteImport } from './routes/members.index'
import { Route as CommitteesIndexRouteImport } from './routes/committees.index'
import { Route as MembersIdRouteImport } from './routes/members.$id'
import { Route as CommitteesIdRouteImport } from './routes/committees.$id'

const ClustersRoute = ClustersRouteImport.update({
  id: '/clusters',
  path: '/clusters',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersIndexRoute = MembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitteesIndexRoute = CommitteesIndexRouteImport.update({
  id: '/committees/',
  path: '/committees/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersIdRoute = MembersIdRouteImport.update({
  id: '/members/$id',
  path: '/members/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitteesIdRoute = CommitteesIdRouteImport.update({
  id: '/committees/$id',
  path: '/committees/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clusters': typeof ClustersRoute
  '/committees/$id': typeof CommitteesIdRoute
  '/members/$id': typeof MembersIdRoute
  '/committees/': typeof CommitteesIndexRoute
  '/members/': typeof MembersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clusters': typeof ClustersRoute
  '/committees/$id': typeof CommitteesIdRoute
  '/members/$id': typeof MembersIdRoute
  '/committees': typeof CommitteesIndexRoute
  '/members': typeof MembersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clusters': typeof ClustersRoute
  '/committees/$id': typeof CommitteesIdRoute
  '/members/$id': typeof MembersIdRoute
  '/committees/': typeof CommitteesIndexRoute
  '/members/': typeof MembersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clusters'
    | '/committees/$id'
    | '/members/$id'
    | '/committees/'
    | '/members/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clusters'
    | '/committees/$id'
    | '/members/$id'
    | '/committees'
    | '/members'
  id:
    | '__root__'
    | '/'
    | '/clusters'
    | '/committees/$id'
    | '/members/$id'
    | '/committees/'
    | '/members/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClustersRoute: typeof ClustersRoute
  CommitteesIdRoute: typeof CommitteesIdRoute
  MembersIdRoute: typeof MembersIdRoute
  CommitteesIndexRoute: typeof CommitteesIndexRoute
  MembersIndexRoute: typeof MembersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/clusters': {
      id: '/clusters'
      path: '/clusters'
      fullPath: '/clusters'
      preLoaderRoute: typeof ClustersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/': {
      id: '/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof MembersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/committees/': {
      id: '/committees/'
      path: '/committees'
      fullPath: '/committees/'
      preLoaderRoute: typeof CommitteesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/$id': {
      id: '/members/$id'
      path: '/members/$id'
      fullPath: '/members/$id'
      preLoaderRoute: typeof MembersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/committees/$id': {
      id: '/committees/$id'
      path: '/committees/$id'
      fullPath: '/committees/$id'
      preLoaderRoute: typeof CommitteesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClustersRoute: ClustersRoute,
  CommitteesIdRoute: CommitteesIdRoute,
  MembersIdRoute: MembersIdRoute,
  CommitteesIndexRoute: CommitteesIndexRoute,
  MembersIndexRoute: MembersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
